# per node local storage
shadow-prefix: "/scratch/local2/{USER}"
# jobscripts
cluster: "mxq-submit.py"
cluster-status: "mxq-status.py"
jobscript: "mxq-jobscript.sh"
# params
latency-wait: 60
jobs: 10000
restart-times: 3
immediate-submit: false
