os: linux
dist: trusty
language: python

python:
    - "3.6"

env:
    - MODULE=alignment

cache:
  bundler: true
  directories:
    - $HOME/docker

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin

deploy:
    script:
        - docker images
        - docker tag $MODULE $DOCKER_USERNAME/$MODULE
        - docker push $DOCKER_USERNAME/$MODULE

jobs:
    include:
        - stage: nanopype base
          env:
              - MODULE=base
              - MODULE=build
          script:
              - docker build -t $MODULE -f singularity/$MODULE/Dockerfile .
        - stage: nanopype modules
          script:
              - docker build -t $MODULE -f singularity/$MODULE/Dockerfile .
        - stage: test
          install:
              - pip install -r requirements.txt
          script:
              - docker run --rm $DOCKER_USERNAME/base python3 -c "import h5py"
