os: linux
dist: trusty
language: python

python:
    - "3.6"

env:
    - MODULE=alignment

#cache:
#  bundler: true
#  directories:
#    - $HOME/docker

after_success:
    - bash <(curl -s https://codecov.io/bash)

before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin

deploy:
    provider: script
    skip_cleanup: true
    script: docker tag $MODULE $DOCKER_USERNAME/$MODULE &&
            docker push $DOCKER_USERNAME/$MODULE &&
            docker images
    on:
        branch: travis

notifications:
  email:
    if: branch = master
    recipients:
      - giesselmann@molgen.mpg.de
    on_success: never
    on_failure: always

jobs:
    include:
        - stage: nanopype base
          env:
              - MODULE=base
          script:
              - docker build -t $MODULE -f singularity/$MODULE/Dockerfile .
        - stage: nanopype build
          env:
              - MODULE=build
          script:
              - docker build -t $MODULE -f singularity/$MODULE/Dockerfile .
        - stage: nanopype modules
          script:
              - docker build -t $MODULE -f singularity/$MODULE/Dockerfile .
        - stage: test
          install:
              - pip install -r requirements.txt
          script:
              - docker run --rm $DOCKER_USERNAME/base python3 -c "import h5py"
