# data paths
storage_data_raw : /project/miniondata/raw
storage_data_import : /project/miniondata/incoming/mpimg_meissner_0

storage_runname:
    delimiter: '_'
    field_ID: 1
    field_flowcell: 2
    filed_kit: 3

# threading
threads_basecalling: 4
threads_alignment: 3
threads_methylation: 4
threads_sv: 4
threads_demux: 4

# basecalling
basecalling_albacore_barcoding: false
basecalling_albacore_disable_filtering: true

# methylation detection
methylation_nanopolish_logp_threshold: 2.5
methylation_nanopolish_aligner: graphmap
methylation_min_coverage: 1

# demux
deepbinner_models:
    default: SQK-RBK004_read_starts
    EXP-NBD103: EXP-NBD103_read_starts
    SQK-RBK004: SQK-RBK004_read_starts
    
