# data paths
DATADIR: /project/miniondata/raw

references:
    mm9:
        genome: /project/bioinf_meissner/references/mm9/mm9.fa
        chr_sizes: /project/bioinf_meissner/references/mm9/mm9.chrom.sizes
    mm10:
        genome: /project/bioinf_meissner/references/mm10/mm10.fa
        chr_sizes: /project/bioinf_meissner/references/mm10/mm10.chrom.sizes
    hg19:
        genome: /project/bioinf_meissner/references/hg19/hg19.fa
        chr_sizes: /project/bioinf_meissner/references/hg19/hg19.chrom.sizes
    hg38:
        genome: /project/bioinf_meissner/references/hg38/hg38.fa
        chr_sizes: /project/bioinf_meissner/references/hg38/hg38.chrom.sizes

# common tool paths
samtools: /project/bioinf_meissner/src/samtools/samtools-1.6/samtools
bedtools: /project/bioinf_meissner/src/bedtools/bedtools/bin/bedtools
ucsctools: /project/bioinf_meissner/src/UCSCtools/

# naopore tool paths
albacore: /project/minion/bin/read_fast5_basecaller.py
minimap2: /project/minion/bin/minimap2
graphmap: /project/minion/bin/graphmap
ngmlr: /project/minion/bin/ngmlr
sniffles: /project/minion/bin/sniffles
nanopolish: /project/minion/bin/nanopolish

# flags
albacore_barcoding: false
min_coverage: 1
