# data paths
storage_data_raw : /data/raw
storage_data_import : /data/import
storage_runname:
    delimiter: '_'
    field_ID: 1
    field_flowcell: 2
    filed_kit: 3

# basecalling
basecalling_albacore_barcoding: false
basecalling_albacore_disable_filtering: true

# methylation detection
methylation_nanopolish_logp_threshold: 2.5
methylation_nanopolish_aligner: graphmap
methylation_min_coverage: 1
