# data paths
data_raw : /project/minion/src/nanopype_dev/build/raw
data_import : /project/miniondata/incoming

# basecalling
albacore_barcoding: false
albacore_disable_filtering: true

# methylation detection
methylation_min_coverage: 1
