site_name: Nanopype
site_description: 'Snakemake pipelines for nanopore sequencing data archiving and processing and analysis'
site_author: 'Pay Giesselmann'
site_url: 'https://nanopype.readthedocs.io'
docs_dir: docs
theme:
  name: 'material'
