# \DOCS\-------------------------------------------------------------------------
#
#  CONTENTS      : MkDocs
#
#  DESCRIPTION   : none
#
#  RESTRICTIONS  : none
#
#  REQUIRES      : none
#
# ---------------------------------------------------------------------------------
# Copyright (c) 2018-2019, Pay Giesselmann, Max Planck Institute for Molecular Genetics
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Written by Pay Giesselmann
# ---------------------------------------------------------------------------------
site_name: Nanopype Documentation
site_description: 'Snakemake pipelines for nanopore sequencing data archiving, processing and analysis'
site_author: 'Pay Giesselmann'
site_url: 'https://nanopype.readthedocs.io'
copyright: 'Copyright &copy; 2018 - 2018 Pay Giesselmann, Max Planck Institute for Molecular Genetics'

repo_name: 'giesselmann/nanopype'
repo_url: 'https://github.com/giesselmann/nanopype/'

docs_dir: docs

# plugins:
    # - pdf-export:
        # verbose: false
        # combined: false
        # media_type: print
        # enabled_if_env: ENABLE_PDF_EXPORT

theme:
  name: 'material'
  include_search_page: false
  search_index_only: true
  logo:
    icon: 'apps'
  static_templates:
    - 404.html

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Getting started: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Modules:
    - Storage: rules/storage.md
    - Basecalling: rules/basecalling.md
    - Alignment: rules/alignment.md
    - Methylation: rules/methylation.md
    - Demultiplexing: rules/demux.md
    - Structural Variation: rules/sv.md
  - Tutorial:
    - Intro : examples/intro.md
    - Data import: examples/import.md
    - Alignment : examples/align.md
#    - Nanopolish: examples/nanopolish.md
#    - Barcoding: examples/demux.md
  - Release notes: release-notes.md
  - Citation: citation.md
  - License: license.md
